controller_manager:
  ros__parameters:
    update_rate: 100
    arm_vel_controller:
      type: velocity_controllers/JointGroupVelocityController
      joints:
        - chassis_yaw_joint
        - arm_1_joint
        - arm_2_joint
    bracket_controller:
      type: position_controllers/JointGroupPositionController
      joints:
        - endpoint_bracket_joint
    gripper_controller:
      type: position_controllers/JointGroupPositionController
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      joints:
        - gripper_left_joint
        - gripper_right_joint

arm_vel_controller:
  ros__parameters:
    joints:
      - chassis_yaw_joint
      - arm_1_joint
      - arm_2_joint

bracket_controller:
  ros__parameters:
    joints:
      - endpoint_bracket_joint

gripper_controller:
  ros__parameters:
    joints:
      - gripper_left_joint
      - gripper_right_joint
